---
title: "Readme"
author: "Garry Grabow"
date: "4/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Brief Description of spreval package
The `spreval` package contains a number of functions to assess irrigation sprinkler system application uniformity and efficiency.  Use of the functions allow for assessment of lateral-move, solid-set, and hose pull (big gun) irrigation systems.

`spreval::catchcan` is a data file included in this package. Data used in the vignettes are taken from the references below:

##References
{Mirriam and Keller, 1978. Farm System Irrigation Evaluation: A Guide for Management.
Form II-1, item 10, p.29.
Utah State University, Logan, Utah. (https://pdf.usaid.gov/pdf_docs/PNAAG745.pdf)

Evans, R.O., Barker J.C., Smith J.T., Sheffield R.E. 1997b.  Field calibration procedures for animal wastewater application equipment, hard hose and cable tow traveler irrigation system. NC Cooperative Extension Service publication  AG-553-2.  Raleigh, NC.
(https://content.ces.ncsu.edu/hard-hose-and-cable-tow-traveler-irrigation-systems)

Evans, R.O., Barker J.C., Smith J.T., Sheffield R.E. 1997a.  Field calibration procedures for animal wastewater application equipment, stationary sprinkler irrigation system. NC Cooperative Extension Service publication AG 553-1.  Raleigh, NC.
(https://irrigation.wordpress.ncsu.edu/files/2017/01/ag-553-1-stationary-sprinkler.pdf)

