title: Speval
description: files for R package speval (sprinkler irrigation uniformity and efficiency functions)
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
